### ISSUE TITLE
Lint .md docs

### ISSUE THREAD

**Issue by leotm** [endojs/endo#2759]
Ref: https://github.com/endojs/endo/pull/2723#discussion_r2029979697

Ensure our .md docs are consistent in style/formatting

1. add root package.json script

e.g.

```json
    "lint:markdown": "markdownlint-cli2 \"**/*.md\"",
```

or include in

https://github.com/endojs/endo/blob/bd964898215adfd4ba46311f0d1fd374c289cba6/package.json#L37

2 ensure running in CI

e.g. 

```yml
name: Markdown lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint:markdown
```

we currently already have a `lint` job so probably want to add it around here

https://github.com/endojs/endo/blob/bd964898215adfd4ba46311f0d1fd374c289cba6/.github/workflows/ci.yml#L47-L56
